### ISSUE TITLE
Could not find 'builder' (~> 3.0.4) - did find: [builder-3.2.2,builder-3.0.0]

### ISSUE THREAD

**Issue by Amadeus-** [GSI/mrmt#2]
In finally getting to the step of using push_contents.rb, I received the error that the 'builder' gem was not installed.    I then tried 'gem install builder' and now I get this error:

```
maestro::root:~/mrmt/lib> ./push_contents.rb ./pages.xml https://URL/ API_KEY
/usr/local/lib/site_ruby/2.1.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'builder' (~> 3.0.4) - did find: [builder-3.2.2,builder-3.0.0] (Gem::LoadError)
Checked in 'GEM_PATH=/root/.gem/ruby/2.1.0:/var/lib/gems/2.1.0:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.1.0:/usr/share/rubygems-integration/2.1.0:/usr/share/rubygems-integration/2.1:/usr/share/rubygems-integration/all', execute `gem env` for more information
        from /usr/local/lib/site_ruby/2.1.0/rubygems/dependency.rb:324:in `to_spec'
        from /usr/local/lib/site_ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:64:in `gem'
        from ./push_contents.rb:5:in `<main>'
Exit 1
maestro::root:~/mrmt/lib> 
```

I don't use ruby very often, so it may very well be something simple; however, I thought I would report it as an issue.

**Comment by Amadeus-** [comment]
I was able to install the specific version of this gem (as well as a few others), so I'm good to go (and will close this issue.)

My only suggestion might be to include in the documentation that specific versions of gems may be required, along with the syntax for installing those gems.  (For those of us who are unfamiliar with ruby!)

**Comment by GSI** [comment]
@Amadeus- did you install **mrmt** via `gem install mrmt` or are you using the source directly (`git clone ...`)?

In case of the latter, could you uninstall the required builder version (thus reproducing the problem) and verify if the first approach works without any hassle?
